### ISSUE TITLE
`sum` and `avg` are not in the functions list

### ISSUE THREAD

**Issue by alvaroaleman** [prometheus/docs#1004]
Hey,

The [functions list](https://prometheus.io/docs/prometheus/latest/querying/functions/) currently does not contain the `sum` and `avg` funcs, I think there should be a note about them

**Comment by simonpasquier** [comment]
This is because they are aggregation operators, not functions. They are thus listed with the [operators](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators).

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
