### ISSUE TITLE
Prometheus server doesn't seem to be recognizing regex group references in `replacement`

### ISSUE THREAD

**Issue by sahilg1** [prometheus/docs#1020]
Given the address to be something like `10.45.22.234:2122`, I want the `instance` label to hold `10.45.22.234` and the `address` to be `10.45.22.234:9274`. 
```
  - source_labels: ['job']
    regex: ^(prometheus-node-exporter).*
    action: keep
  - source_labels: [__address__]
    regex: ^(.*):(.*)$
    target_label: instance
    replacement: ${1}
  - source_labels: [__address__]
    regex: ^(.*):(.*)$
    target_label: __address__
    replacement: ${1}:9274
```
I have also tried using `'$1:9274'` and `$1:9274` in the `replacement` but nothing seems to work.
Right now all I am getting is `instance=":9274"` and `address=http://:9274/metrics`

In another case, I have config - 
```
  - source_labels: ['job']
    regex: ^(blackbox-exporter).*
    action: keep
  - source_labels: [__address__]
    regex: ^(.*):(.*)$
    target_label: instance
    replacement: ${1}
```
Here it spits `instance="10.45.22.234:2122"` (It doesn't parse out the group reference and gives the whole address)
Version -  v2.2.1 
I have been stuck with this for a while, appreciate any help!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
