### ISSUE TITLE
Add proxy exporter pattern explanation

### ISSUE THREAD

**Issue by vonneudeck** [prometheus/docs#1193]
The blackbox, SNMP and IPMI exporter make use of the proxy exporter pattern, which is in itself special enough to be explained to clarify their usage.

The proxy pattern is that the exporter is getting the target and the module to apply on it via an HTTP GET request from Prometheus and then starts its own request over network and returns the answer with the HTTP request response. In practice this often coupled with using relabeling in the Prometheus config.yml that is not trivial, especially for people new to Prometheus.

The blackbox exporter will be used as an example as it is:
- introducing no second protocol
- the most popular of those three according to docker hub statistics
- often used with relabeling

The purpose is neither a complete step-by-step guide nor a complete reference. It should enable people who have not heard of the proxy pattern before to deploy and configure such exporters and Prometheus to do something useful for them.

This explanation will be linked to by the SNMP exporter explanation #1192 .

As proposed on the [users mailing list](https://groups.google.com/d/msg/prometheus-users/jFsTY8g3pk8/nG5Ua0pcCgAJ) and announced on the [devs mailing list](https://groups.google.com/d/msg/prometheus-developers/edSzZuPI7Mc/VoWpl61_BAAJ) I want to write these explanations, but help is very welcome.

**Comment by brian-brazil** [comment]
> proxy exporter pattern

There's no such term used in the project, and all exporters are fundamentally proxies so the name would be confusing.

**Comment by brian-brazil** [comment]
I also find proxy exporter to be acceptable for exporters that are 1:1 with their targets, and commonly explain exporters as being proxies.

**Comment by SuperQ** [comment]
I usually call them sidecars, or sidecar exporters. This is a more common term used by Kubernetes users.

**Comment by brian-brazil** [comment]
I suggest we find a different term, sidecar is a bit k8 specific. Maybe multi-target or provided target?

**Comment by RichiH** [comment]
The fundamental difference between node_exporter, snmp_exporter, and ipmi_exporter is that they are 1:1, 1:n, and 1:1/n, respectively. That's the reason why I dislike ipmi_exporter's design decision.

I would also call it multi-target, multiplexer, 1:n, or something along those terms.

As we are mangling data, I would propose `1:n` as the official term; this is well-defined in the DB and data structure world.

**Comment by vonneudeck** [comment]
Sorry, I pressed the button accidentally.

**Comment by matthiasr** [comment]
I like "proxy exporter". That there is no such term yet is not an argument, since obviously we have not named the concept yet even though we agree that the concept exists.

Just saying that "everything is an exporter" makes nothing clearer.

Taking the terminology from HTTP, the blackbox and SNMP exporter are proxies, while regular exporters are more like reverse proxies, so I don't see the term applybto both equally. and even if that was the case we can choose what to use it for.

**Comment by RichiH** [comment]
I don't think [reverse] proxies behave fundamentally different from either type of exporter and as such "proxy exporter" is not really distinctive either. I would still suggest `1:1 exporter` and `1:n exporter` as those are well-defined and exact in their meaning.

**Comment by juliusv** [comment]
I also don't think "proxy exporter" is a distinctive enough term, since it could as well just describe any exporter. Instead of having numbers and special chars in a name like in "1:1 exporter" and "1:n exporter", I would prefer something that's mostly letters, like "Fanout exporter" or "Multi-target exporter". Probably of those, I like "Multi-target exporter" most.

**Comment by SuperQ** [comment]
Thanks @juliusv, I like those suggestions. :+1: for "Multi-target exporter"

**Comment by vonneudeck** [comment]
I think "multi-target exporter" is a very good name. Anyone strongly opposed?

**Comment by vonneudeck** [comment]
The guide has been merged 🥳
