### ISSUE TITLE
Prometheus debug level extreme?

### ISSUE THREAD

**Issue by augmenter** [prometheus/docs#1263]
Would it be possible to add a higher log level than debug? I am developing a custom exporter for my web app and it ran fine for a few months. The export labels are dynamic and I think that some values might get output to the matrics that confuse prometheus. Under targets it still shows up as UP, but no data is collected. If metrics output is empty it would still show as UP, maybe it could show how many stats were collected in total on last scrape: 0 or 10k?Should I just try to use an exising php library to create metrics to achieve 100% compatibility?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
