### ISSUE TITLE
Rule-Checker documentation outdated

### ISSUE THREAD

**Issue by Luzifer** [prometheus/docs#130]
In ["Recording rules"](https://github.com/prometheus/docs/blob/master/content/docs/querying/rules.md#syntax-checking-rules) the `rule_checker` tool is referenced but according to [CHANGELOG](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md) the tool has been replaced and is not longer `go get`-able.

**Comment by fabxc** [comment]
Yup, this is true for `master`. However, our documentation refers to the latest release which is 0.14.0, which still contains the `rule_checker` tool.

At some point we have to look into versioned docs but those are not yet feasible.

But this is a good reminder that we have to adjust our "Getting started" docs so people use the latest release rather than `master`. /cc @juliusv

**Comment by juliusv** [comment]
https://github.com/prometheus/docs/pull/131 addresses this. We can already use `promtool` for everyone, since it should also work with old versions.

**Comment by juliusv** [comment]
Was fixed a while ago in https://github.com/prometheus/docs/pull/131.
