### ISSUE TITLE
Label usage confuse

### ISSUE THREAD

**Issue by VShox** [prometheus/docs#1407]
`Every time series is uniquely identified by its metric name and optional key-value pairs called labels.` - so looks like I can create a counter "counter_name" with label: `key1 => value1` and it will create this time series determined by couner_name + key1.
And another unique series will be created with using the same counter name but different labels: counter "counter_name" with labels: "key1 => value1, key2 => value2"  

Then later it confirmed by doc:
`Changing any label value, including adding or removing a label, will create a new time series.`
But on another article in the same documentation we see:
`Client libraries MUST NOT under any circumstances allow users to have different label names for the same metric for Gauge/Counter/Summary/Histogram or any other Collector offered by the library.`

It confuses that if client add or remove label - it will create new time series (for the same metric name) - but in the same time it MUST NOT be allowed.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
