### ISSUE TITLE
Multi query alertmanager or grafana

### ISSUE THREAD

**Issue by razumv** [prometheus/docs#1408]
Hello. I have a openshift cluster monitoring. All is OK.
I need a send metrics of CPU, memory when openshift POD is restarts. Help me please)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
