### ISSUE TITLE
Is it possible to configure bearer_token/bearer_token_file in encrypted form?

### ISSUE THREAD

**Issue by sumanaps** [prometheus/docs#1433]
Need to configure the K8s cluster metric scraping in Prometheus running outside the cluster... For this am using 'kubernetes_sd_config' configuration... 

From the Prometheus guide looks like the bearer_token/bearer_token_file supports only bearer tokens in plain text format... 
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read 

As K8s serviceaccount tokens are valid forever, if token is compromised will be a major security concern... 

Apart from the restricted file permissions for the token file, is there any way to avoid the plain text access_token in bearer_token/bearer_token_file fields...

**Comment by brian-brazil** [comment]
There's not, and this is how Kubernetes provides tokens in any case.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by sumanaps** [comment]
Ok... Thanks...
