### ISSUE TITLE
Unable to use TLS in prometheus with spring boot 

### ISSUE THREAD

**Issue by dineshv1234567** [prometheus/docs#1494]
I am trying to fetch metrics from API-gateway (Spring boot microservice) using Prometheus. API gateway contains a self-signed certificate signed by the CA authority so as to make it https. As per docs, TLS is not fully implemented but till now reverse proxy part can be used as suggested by others on the web. 

I followed the link : 
https://jaas.ai/docs/collecting-juju-metrics

And added CA signed cert, private key, and CA cert in Prometheus deployment YAML file but still not able to fetch metrics. 

Can please anyone help me out or give some example file so that I can do the same.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
