### ISSUE TITLE
kubernetes_sd_configs and associated metrics

### ISSUE THREAD

**Issue by aceeric** [prometheus/docs#1498]
Is there a way to know which `kubernetes_sd_configs` role (e.g. pod, node, etc.) provides which metric(s)? The context of the question is: we are cloning/modiyfing a Strimzi Kafka Grafana dashboard. The dashboard references a Prometheus metric `container_memory_usage_bytes`. There are several `-job_name` entries in the Prometheus scrape configuration with associated `kubernetes_sd_configs` but - which config provides the metric in question?

The goal is to customize the scraping and the associated dashboards.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
