### ISSUE TITLE
What is the definition of $value in an alert template?

### ISSUE THREAD

**Issue by alexr-plutoflume** [prometheus/docs#1601]
https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/

"The $value variable holds the evaluated value of an alert instance."

It would be great if this also included a more explicit definition. Is it everything to the left of the comparison operator in the expr?

**Comment by brian-brazil** [comment]
It's exactly what it says, the value. Comparison operators are orthogonal.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
