### ISSUE TITLE
What is the difference between k8s_POD and k8s_prometheus?

### ISSUE THREAD

**Issue by davesargrad** [prometheus/docs#1605]
In the following I see two "prometheus-deployments" (prefixes, _k8s_POD_ and _k8s_prometheus_).  

![image](https://user-images.githubusercontent.com/48793689/79868342-c53e5980-83ad-11ea-8ec9-27668a5ec381.png)

They both seem to respond to the same executing prometheus deployment.
![image](https://user-images.githubusercontent.com/48793689/79868448-ea32cc80-83ad-11ea-8075-bbb0f66b230f.png)

Only one of these seems to have interesting data (_k8s_prometheus_).
![image](https://user-images.githubusercontent.com/48793689/79868391-d4250c00-83ad-11ea-881c-bd98937e6035.png)

Can someone please explain their difference? I dont seem to see anything in the documentation that describes this kind of pertinent detail. If you have a reference to such documentation, I'd appreciate it.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by davesargrad** [comment]
@brian-brazil Done. Ty for that suggestion.

**Comment by davesargrad** [comment]
https://groups.google.com/forum/#!topic/prometheus-users/8Cl32p5gHDE
