### ISSUE TITLE
Request: Please provide an example of an error in the text-based exposition format

### ISSUE THREAD

**Issue by vivekKodira** [prometheus/docs#1644]
Hello,

With regard to [this page](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format), would you please add an example of what should be logged against a metric in case of an error? 

What is the prometheus's recommendation: Should the metric not be logged or an error put in place of the metric value?

**Comment by brian-brazil** [comment]
This is covered over in https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes

**Comment by vivekKodira** [comment]
@brian-brazil Sorry if I wasn't clearer. I'm asking what to log to the file in case a metric cannot be fetched. The link seems to deal with something else.

**Comment by brian-brazil** [comment]
I'm not quite understanding you, this sounds more like it's a usage question and 
it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vivekKodira** [comment]
Thanks Brian. For anyone else with this issue, there is indeed an example [here](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md) that I had missed:

The error is passed as a label.
`msdos_file_access_time_seconds{path="C:\\DIR\\FILE.TXT",error="Cannot find file:\n\"FILE.TXT\""} 1.458255915e9`
