### ISSUE TITLE
Removing unnecessary Slack channel settings

### ISSUE THREAD

**Issue by iaoiui** [prometheus/docs#1674]
I found the sample configuration for slack integration on following document.
https://prometheus.io/docs/alerting/latest/notification_examples/#customizing-slack-notifications

The slack webhooks url is tied to the slack channel, so I don't personally think the channel setting in slack_configs is necessary.
What is your intention in leaving this setting in place?

![image](https://user-images.githubusercontent.com/6523614/84784465-4e2be700-b025-11ea-9d14-a41fb49deede.png)

Thank you

**Comment by brian-brazil** [comment]
It depends on the type of webhook on the slack side, not all are restricted to only one channel.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
