### ISSUE TITLE
Bad documentation to install prometheus 1.0.1

### ISSUE THREAD

**Issue by Tumite** [prometheus/docs#1695]
Hi team!

I would like to install prometheus from this doc: https://prometheus.io/docs/guides/node-exporter/
but i got missing tls config error message. I tired other docs from the internet but i can't install normally new version, just from apt: https://linuxhint.com/install-prometheus-ubuntu-18-04/

Any help?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
