### ISSUE TITLE
Will alertmanager support output to flock ?

### ISSUE THREAD

**Issue by Daych** [prometheus/docs#1726]
We would like to use the flock instead of slack of the alerting, Flock supporting income webhook for another alerting application, I tested the Zabbix also supported to use.

I used the slack_configs for my Slack is working, for the webhook_configs also didnt works for the Flock, do alertmanager will support or I missed something ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Daych** [comment]
I had asked this question on prometheus-users, but no one back to me, so I asked here.
