### ISSUE TITLE
why standard deviation is statistically useless ?

### ISSUE THREAD

**Issue by nous23** [prometheus/docs#1733]
https://prometheus.io/docs/instrumenting/writing_exporters/#drop-less-useful-statistics

it said "the standard deviation is statistically useless and you can always expose sum of squares, _sum and _count if you ever need to calculate it."

why standard deviation is statistically useless ?
and can sum of squares replace standard deviation ?

**Comment by brian-brazil** [comment]
I can't be aggregated, and an issue tracker is not the place for statistics questions. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
