### ISSUE TITLE
/docs/content/docs/prometheus contents are missing from repo 

### ISSUE THREAD

**Issue by Mldhun** [prometheus/docs#1776]
/docs/content/docs/prometheus   ---> This directory not showing any contents except index.md in Repo. 

```
[midhun.k@ibllsomidhunk prometheus]$ pwd
/home/midhun.k/docs/content/docs/prometheus
[midhun.k@ibllsomidhunk prometheus]$ ls
index.md
```

**Comment by brian-brazil** [comment]
That's correct, it's included at site build time from the main prometheus repo.

It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
