### ISSUE TITLE
file_sd param meta label

### ISSUE THREAD

**Issue by dustypc101** [prometheus/docs#1831]
I am converting my scrape configs to file_sd configs.  I have found through some extensive searching that I can use meta labels in the file_sd files.  Can the correct process to do this be included in the documentation?  Or is this not supported but works?  
The current issue I am facing is in migrating this working scrape to a file sd scrape:
   - job_name: 'agile'
      scheme: https
      metrics_path: 'plugins/servlet/prometheus/metrics'
      params:
        token: ['mytoken']
      static_configs:
        - targets: ['myserver:port']
           labels:
              host: 'myserver'

File sd scrape:
- targets:
  - myserver:port
  labels:
    job: agile
    __metrics_path__: 'plugins/servlet/prometheus/metrics'
    __scheme__: https
    __params_token__: ['mytoken']

I always get an unmarshall error on the value of params_token.  I imagine this is because the syntax is not correct.
If this is documented somewhere please point me in that direction.

Thank you!

**Comment by brian-brazil** [comment]
This is documented at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config and https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
