### ISSUE TITLE
Unmatched values from 'kubectl top nodes' and prometheus UI.

### ISSUE THREAD

**Issue by AkshayAwate** [prometheus/docs#1862]
I m getting unmatched value from top command and prometheus.
The expression:  avg(rate(node_cpu_seconds_total[1m])) by (node).
I have 3 worker nodes, i wanna calculate cpu usage by each node.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
