### ISSUE TITLE
Table of contents conflicts with `NOTE` box

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/docs#1986]
This issue appears in:

* https://prometheus.io/docs/guides/go-application/
* https://prometheus.io/docs/guides/node-exporter/
* https://prometheus.io/docs/guides/basic-auth/
* https://prometheus.io/docs/guides/basic-auth/

(tested in Chrome and Firefox)

![image](https://user-images.githubusercontent.com/54278938/124687018-2878b680-dea2-11eb-961e-a1825c72577a.png)

**Comment by RichiH** [comment]
Thanks for the report, reproduced locally in Chromium.

@grobie @juliusv this seems to be new?

**Comment by juliusv** [comment]
It's because the NOTE block is a `div` which is a `display: block` element, which is 100% width by default and also doesn't seem to care about overlapping the float element.

Adding `display: inline-block; width: 100%;` to the note block seems to help with this particular situation:

![note-inline-block](https://user-images.githubusercontent.com/538008/124835000-e96d6280-df80-11eb-96d9-733b97fd5ed0.png)

I also tried to add a `clear: ...` with different values to the TOC div, but that also then moves the paragraph text out of the way in a way we don't want.
