### ISSUE TITLE
Tag documentation with prometheus releases

### ISSUE THREAD

**Issue by lmb** [prometheus/docs#464]
Seems like there is no good way to go to the correct documentation for a given prometheus release at the moment. Would it be possible to add tags on prometheus releases to this repo going forward?

Brownie points if old documentation was kept accessible on the website as well.

**Comment by fabxc** [comment]
Yes, we really need that. As we have documentation for Alertmanager and Prometheus, these should work independently.

The working approach in general seems to be copy all documentation on each release into a new folder named after the respective version.
So that at any time HEAD contains documentation for each release.

**Comment by brian-brazil** [comment]
This is done.
