### ISSUE TITLE
www.prometheus.io does not work

### ISSUE THREAD

**Issue by girishkalele** [prometheus/docs#533]
prometheus.io works, but www.prometheus.io does not.

`404 Not Found

Nothing matches the given URI
`

**Comment by juliusv** [comment]
Thanks! Taking a look...

**Comment by juliusv** [comment]
Fixed! www.prometheus.io was still pointing to the old Gandi web redirector in CloudFlare, but the prometheus.io domain recently moved from Gandi to somewhere else, so that redirector stopped working.

I changed the CNAME in CloudFlare to redirect www.prometheus.io directly to prometheus.io. Seems to be all working now.

Thanks again!
