### ISSUE TITLE
404  for https://prometheus.io/docs/visualization/promdash/

### ISSUE THREAD

**Issue by abuehrle** [prometheus/docs#684]
When googling prometheus dashboards, the first link I get is a link to PromDash, but it 404's. You might want to include a redirect for that. 

https://prometheus.io/docs/visualization/promdash/

**Comment by juliusv** [comment]
We just removed that page today, so Google probably just didn't get a chance to notice yet. Let's wait and see if search engines pick up the changes quickly enough?

**Comment by grobie** [comment]
Damn, that was fast. I wondered if we need to handle references to the
promdash page and decided I'll ignore that until it comes up as an issue
... Is there any way to configure 30x redirects for github pages?

Otherwise we could through in a meta refresh tag again, but that doesn't
help search engines. Would be an option though.

**Comment by juliusv** [comment]
I don't think 30x is possible, since it's just a static file server. I'd be cool with meta tags. But who knows, maybe Google forgets reasonably quickly?

**Comment by abuehrle** [comment]
We used meta tags with our guides awhile back. I don't think it's the best practise, but it's better to do something, since other people might be linked to your docs with that link in a blog or something.  That's the main issue.

**Comment by brian-brazil** [comment]
That link is no longer showing up on Google.
