### ISSUE TITLE
Fix HTML syntax errors in anchor names

### ISSUE THREAD

**Issue by discordianfish** [prometheus/docs#833]
Dunno if it's worth fixing all html syntax issues but we should at least fix the anchor names because right now it forces people linking to the docs to use invalid syntax:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fprometheus.io%2Fdocs%2Foperating%2Fconfiguration%2F

```
Error: Bad value #<duration> for attribute href on element a: Illegal character in fragment: < is not allowed.
From line 241, column 22; to line 241, column 49
interval: <a href="#&lt;duration&gt;">&lt;du
```

**Comment by derrickaw** [comment]
Hey @lucperkins, noticed you self-assigned this one to yourself.  Since its been a few months, do you mind if I take a crack at this one instead?  Thanks

**Comment by lucperkins** [comment]
@derrickaw Sure, go for it! Sorry, this fell off my radar due to other projects.

**Comment by derrickaw** [comment]
@lucperkins Sorry, I thought I knew how to fix this issue and that it was a simple html change :), but it looks like the markdown is converted to html.  If you had some pointers on which files to update or how the building of the html works I will continue looking at it, otherwise, feel free to take it back.  Sorry again.

**Comment by dkurzaj** [comment]
Since it is not a valid syntax it breaks the use of the documentation in Firefox and Chromium (the two browser I've tested). When we click on an anchor link, it simply does not redirect us to the right part of the documentation, so this bug kind of breaks the documentation website. It is not usable as intended.

**Comment by pracucci** [comment]
@discordianfish This issue should have just been fixed by https://github.com/prometheus/docs/pull/1382. Do you mind double checking it, please?

**Comment by discordianfish** [comment]
Yeah I think this is fixed. Thanks for the ping!
